// ---------------------------------------------------------------------------
// Meaning Blitz words. Written by hand (not generated) so the clues give a
// nudge without giving the answer away.
//
//   rare.en / rare.fr — little-known dictionary words, played in rooms of that
//                       language. Each has a short clue.
//   foreign           — words from other languages. Players are told which
//                       language; there is no clue. A room never gets words
//                       in its own language here.
//
// `meaning` is shown after the round and is what answers are graded against.
// `keywords` are only used to grade roughly when the AI grader can't be
// reached (see meaning-grade.mjs).
// ---------------------------------------------------------------------------

export const LANG_NAMES = {
  ak: { en: 'Akan (Twi)', fr: 'akan (twi)' },
  ar: { en: 'Arabic', fr: 'arabe' },
  cy: { en: 'Welsh', fr: 'gallois' },
  da: { en: 'Danish', fr: 'danois' },
  de: { en: 'German', fr: 'allemand' },
  el: { en: 'Greek', fr: 'grec' },
  en: { en: 'English', fr: 'anglais' },
  es: { en: 'Spanish', fr: 'espagnol' },
  fi: { en: 'Finnish', fr: 'finnois' },
  fr: { en: 'French', fr: 'français' },
  haw: { en: 'Hawaiian', fr: 'hawaïen' },
  hi: { en: 'Hindi', fr: 'hindi' },
  id: { en: 'Indonesian', fr: 'indonésien' },
  it: { en: 'Italian', fr: 'italien' },
  iu: { en: 'Inuktitut', fr: 'inuktitut' },
  ja: { en: 'Japanese', fr: 'japonais' },
  ln: { en: 'Lingala', fr: 'lingala' },
  nl: { en: 'Dutch', fr: 'néerlandais' },
  no: { en: 'Norwegian', fr: 'norvégien' },
  pt: { en: 'Portuguese', fr: 'portugais' },
  ru: { en: 'Russian', fr: 'russe' },
  sco: { en: 'Scots', fr: 'scots (écossais)' },
  sv: { en: 'Swedish', fr: 'suédois' },
  sw: { en: 'Swahili', fr: 'swahili' },
  tl: { en: 'Tagalog', fr: 'tagalog' },
  wo: { en: 'Wolof', fr: 'wolof' },
  yag: { en: 'Yaghan', fr: 'yagan' },
  yi: { en: 'Yiddish', fr: 'yiddish' },
  zu: { en: 'Zulu', fr: 'zoulou' },
};

const w = (word, lang, clue, meaning, keywords) => ({ word, lang, clue, meaning, keywords });
const f = (word, lang, meaning, keywords) => ({ word, lang, clue: null, meaning, keywords });

export const RARE = {
  en: [
    w('petrichor', 'en',
      { en: 'Your nose knows it after a storm', fr: 'Votre nez le connaît après l’orage' },
      { en: 'The pleasant, earthy smell after rain falls on dry ground.', fr: 'L’odeur agréable de terre mouillée quand la pluie tombe sur un sol sec.' },
      ['smell', 'scent', 'rain', 'earth', 'odeur', 'pluie', 'terre']),
    w('defenestration', 'en',
      { en: 'There’s a window involved — and it’s not nice', fr: 'Il y a une fenêtre… et ce n’est pas gentil' },
      { en: 'The act of throwing someone or something out of a window.', fr: 'Le fait de jeter quelqu’un ou quelque chose par la fenêtre.' },
      ['throw', 'window', 'jeter', 'fenetre']),
    w('borborygmus', 'en',
      { en: 'Your belly might make one when you’re hungry', fr: 'Votre ventre en fait quand vous avez faim' },
      { en: 'A rumbling or gurgling noise made by the stomach or intestines.', fr: 'Un gargouillement du ventre ou des intestins.' },
      ['stomach', 'belly', 'rumble', 'gurgle', 'noise', 'ventre', 'gargouill', 'bruit']),
    w('apricity', 'en',
      { en: 'Something lovely to feel on a cold day', fr: 'Agréable à sentir par une journée froide' },
      { en: 'The warmth of the sun in winter.', fr: 'La chaleur du soleil en hiver.' },
      ['sun', 'warm', 'winter', 'soleil', 'chaleur', 'hiver']),
    w('crapulence', 'en',
      { en: 'How you might feel after a huge party dinner', fr: 'Ce qu’on ressent après un énorme repas de fête' },
      { en: 'Feeling sick from eating or drinking too much.', fr: 'Le malaise qu’on ressent après avoir trop mangé ou trop bu.' },
      ['sick', 'eat', 'drink', 'too much', 'malade', 'malaise', 'manger', 'boire', 'trop']),
    w('susurrus', 'en',
      { en: 'You have to listen closely to hear it', fr: 'Il faut tendre l’oreille pour l’entendre' },
      { en: 'A soft whispering or rustling sound.', fr: 'Un doux murmure ou bruissement.' },
      ['whisper', 'rustl', 'murmur', 'soft', 'chuchot', 'bruissement']),
    w('ultracrepidarian', 'en',
      { en: 'Think of a know-it-all', fr: 'Pensez à un « je-sais-tout »' },
      { en: 'Someone who gives opinions on things they know nothing about.', fr: 'Quelqu’un qui donne son avis sur des sujets qu’il ne connaît pas.' },
      ['opinion', 'know', 'expert', 'advice', 'avis', 'connai', 'sujet']),
    w('gobbledygook', 'en',
      { en: 'Often found in official letters', fr: 'On en trouve souvent dans les courriers officiels' },
      { en: 'Language that is meaningless or hard to understand, like heavy jargon.', fr: 'Un langage incompréhensible ou jargonneux ; du charabia.' },
      ['nonsense', 'jargon', 'meaningless', 'gibberish', 'charabia', 'incomprehensible']),
    w('lollygag', 'en',
      { en: 'What you do instead of hurrying', fr: 'Ce qu’on fait au lieu de se dépêcher' },
      { en: 'To waste time doing nothing useful; to dawdle.', fr: 'Perdre son temps à ne rien faire d’utile ; traîner.' },
      ['waste time', 'dawdle', 'idle', 'lazy', 'nothing', 'trainer', 'flaner', 'perdre']),
    w('snollygoster', 'en',
      { en: 'You might meet one in politics', fr: 'On en croise en politique' },
      { en: 'A clever but dishonest person, especially a politician.', fr: 'Une personne habile mais malhonnête, surtout un politicien.' },
      ['dishonest', 'politic', 'crook', 'shrewd', 'malhonnete', 'politicien', 'escroc']),
    w('kerfuffle', 'en',
      { en: 'Lots of noise about not much', fr: 'Beaucoup de bruit pour pas grand-chose' },
      { en: 'A commotion or fuss, often caused by a disagreement.', fr: 'Une agitation ou une histoire, souvent née d’un désaccord.' },
      ['fuss', 'commotion', 'chaos', 'dispute', 'disagree', 'agitation', 'histoire', 'remue']),
    w('discombobulate', 'en',
      { en: 'What a surprise quiz can do to you', fr: 'L’effet d’une interro surprise' },
      { en: 'To confuse or disconcert someone.', fr: 'Déconcerter ou embrouiller quelqu’un.' },
      ['confus', 'disorient', 'disconcert', 'deconcert', 'embrouill', 'perturb']),
    w('collywobbles', 'en',
      { en: 'Might strike right before an exam', fr: 'Peut frapper juste avant un examen' },
      { en: 'Nervousness or anxiety, often felt as a stomach ache.', fr: 'Nervosité ou angoisse, souvent ressentie comme un mal de ventre.' },
      ['nerv', 'anxi', 'stomach', 'butterflies', 'angoisse', 'ventre', 'trac']),
    w('pandiculation', 'en',
      { en: 'You probably do it when you wake up', fr: 'Vous le faites sans doute au réveil' },
      { en: 'Stretching the body and yawning, especially when tired or waking up.', fr: 'S’étirer en bâillant, surtout quand on est fatigué ou au réveil.' },
      ['stretch', 'yawn', 'etir', 'baill']),
    w('sesquipedalian', 'en',
      { en: 'This very word is an example of it', fr: 'Ce mot-là en est lui-même un exemple' },
      { en: 'Using long words, or (of a word) very long with many syllables.', fr: 'Qui emploie des mots très longs, ou (pour un mot) très long.' },
      ['long word', 'syllable', 'mots longs', 'long']),
    w('quidnunc', 'en',
      { en: 'They’d love to hear your latest news', fr: 'Adore connaître les dernières nouvelles' },
      { en: 'A nosy person who always wants to know the latest gossip.', fr: 'Une personne curieuse qui veut toujours connaître les derniers potins.' },
      ['gossip', 'nosy', 'curious', 'busybody', 'commere', 'curieu', 'potin']),
    w('flibbertigibbet', 'en',
      { en: 'Not someone you’d trust with a serious job', fr: 'Pas quelqu’un à qui confier un travail sérieux' },
      { en: 'A silly, flighty person who talks too much.', fr: 'Une personne frivole et écervelée qui parle trop.' },
      ['frivolous', 'flighty', 'silly', 'chatter', 'scatter', 'ecervel', 'bavard', 'frivole']),
    w('absquatulate', 'en',
      { en: 'Something you do when the party gets boring', fr: 'Ce qu’on fait quand la fête devient ennuyeuse' },
      { en: 'To leave suddenly or run away.', fr: 'Partir brusquement ; s’enfuir.' },
      ['leave', 'run away', 'flee', 'escape', 'partir', 'enfuir', 'filer', 'fuir']),
    w('mondegreen', 'en',
      { en: 'Happens a lot with song lyrics', fr: 'Arrive souvent avec les paroles de chansons' },
      { en: 'A word or phrase that is misheard, especially in a song.', fr: 'Un mot ou une phrase mal entendus, surtout dans une chanson.' },
      ['mishear', 'misheard', 'lyric', 'song', 'mal entendu', 'paroles', 'chanson']),
    w('tittle', 'en',
      { en: 'There’s one on this letter: i', fr: 'Il y en a un sur cette lettre : i' },
      { en: 'The small dot over a lowercase i or j.', fr: 'Le petit point sur un i ou un j minuscule.' },
      ['dot', 'point']),
    w('serendipity', 'en',
      { en: 'Finding a banknote in an old coat', fr: 'Trouver un billet dans un vieux manteau' },
      { en: 'Finding something good by chance, without looking for it.', fr: 'Faire une heureuse découverte par hasard, sans la chercher.' },
      ['chance', 'luck', 'accident', 'fortun', 'hasard', 'decouverte']),
    w('ephemeral', 'en',
      { en: 'Like a soap bubble', fr: 'Comme une bulle de savon' },
      { en: 'Lasting a very short time.', fr: 'Qui dure très peu de temps.' },
      ['short', 'brief', 'temporary', 'fleeting', 'court', 'bref', 'passager', 'temporaire']),
    w('obfuscate', 'en',
      { en: 'Politicians do it to dodge a question', fr: 'Les politiciens le font pour esquiver une question' },
      { en: 'To make something unclear or hard to understand on purpose.', fr: 'Rendre volontairement quelque chose obscur ou difficile à comprendre.' },
      ['confus', 'unclear', 'obscur', 'hide', 'embrouill', 'cacher', 'flou']),
    w('cacophony', 'en',
      { en: 'A band of toddlers with drums', fr: 'Une fanfare de bambins avec des tambours' },
      { en: 'A harsh, unpleasant mix of sounds.', fr: 'Un mélange de sons désagréable et discordant.' },
      ['noise', 'harsh', 'sound', 'racket', 'bruit', 'vacarme', 'son']),
    w('lackadaisical', 'en',
      { en: 'Not how you should prepare for a final exam', fr: 'Pas la bonne façon de réviser un examen final' },
      { en: 'Lacking enthusiasm and effort; lazily careless.', fr: 'Sans entrain ni effort ; nonchalant.' },
      ['lazy', 'careless', 'enthusias', 'effort', 'nonchalant', 'paresseu', 'mou']),
    w('nudiustertian', 'en',
      { en: 'It has to do with a day', fr: 'Ça concerne un jour' },
      { en: 'Relating to the day before yesterday.', fr: 'Qui se rapporte à avant-hier.' },
      ['day before yesterday', 'avant-hier', 'avant hier']),
    w('gubbins', 'en',
      { en: 'The stuff at the bottom of your bag', fr: 'Ce qu’on trouve au fond de son sac' },
      { en: 'Odds and ends; miscellaneous bits and pieces or gadgets.', fr: 'Un bric-à-brac de petites choses diverses ; des bidules.' },
      ['bits', 'stuff', 'odds', 'gadget', 'thing', 'truc', 'bricole', 'bazar', 'bidule']),
    w('brouhaha', 'en',
      { en: 'What a crowd does when something unexpected happens', fr: 'Ce que fait une foule face à l’inattendu' },
      { en: 'A noisy, excited reaction or commotion.', fr: 'Un bruit confus et agité ; un tumulte.' },
      ['uproar', 'commotion', 'noise', 'fuss', 'tumulte', 'vacarme', 'agitation', 'bruit']),
  ],
  fr: [
    w('vergogne', 'fr',
      { en: 'Mostly used after “sans”', fr: 'S’emploie surtout après « sans »' },
      { en: 'Shame or a sense of decency (mostly in “sans vergogne”: shamelessly).', fr: 'Honte, pudeur (surtout dans « sans vergogne » : sans scrupule).' },
      ['shame', 'decency', 'scruple', 'honte', 'pudeur', 'scrupule']),
    w('faribole', 'fr',
      { en: 'What you might call a tall story', fr: 'Ce qu’on dit d’une histoire à dormir debout' },
      { en: 'Silly, frivolous talk; nonsense.', fr: 'Propos frivole, sans importance ; baliverne.' },
      ['nonsense', 'silly', 'baliverne', 'betise', 'sottise', 'sornette']),
    w('billevesée', 'fr',
      { en: 'A close cousin of “faribole”', fr: 'Une proche cousine de la « faribole »' },
      { en: 'An empty, silly idea or talk; nonsense.', fr: 'Idée creuse, propos chimérique ; sornette.' },
      ['nonsense', 'silly', 'empty', 'sornette', 'baliverne', 'creu', 'chimer']),
    w('pusillanime', 'fr',
      { en: 'Not the word you’d use for a hero', fr: 'Pas le mot qu’on emploie pour un héros' },
      { en: 'Lacking courage; timid and cowardly.', fr: 'Qui manque de courage ; craintif, lâche.' },
      ['coward', 'timid', 'courage', 'fear', 'lache', 'peureu', 'craintif']),
    w('sycophante', 'fr',
      { en: 'Careful: it doesn’t mean the same as in English', fr: 'Attention : en anglais, il ne veut pas dire la même chose' },
      { en: 'An informer who denounces others; a slanderer.', fr: 'Délateur, dénonciateur ; calomniateur.' },
      ['informer', 'snitch', 'denounc', 'slander', 'delateur', 'denonc', 'mouchard', 'calomni']),
    w('atermoiement', 'fr',
      { en: 'The opposite of deciding right away', fr: 'Le contraire de décider tout de suite' },
      { en: 'Putting off a decision; delay (usually used in the plural).', fr: 'Action de remettre une décision à plus tard (souvent au pluriel).' },
      ['delay', 'postpone', 'procrastinat', 'hesitat', 'retard', 'remettre', 'tergivers']),
    w('tergiverser', 'fr',
      { en: 'What someone does who never gives a straight answer', fr: 'Ce que fait quelqu’un qui ne répond jamais franchement' },
      { en: 'To hesitate and use evasions to avoid making a decision.', fr: 'Hésiter, user de détours pour éviter de prendre une décision.' },
      ['hesitat', 'evade', 'dodge', 'waver', 'hesiter', 'detour', 'eviter']),
    w('ripaille', 'fr',
      { en: 'Often said with “faire”', fr: 'Se dit souvent avec « faire »' },
      { en: 'A feast with lots of food and drink.', fr: 'Repas où l’on mange et boit abondamment ; festin.' },
      ['feast', 'banquet', 'eat', 'festin', 'bombance', 'repas', 'manger']),
    w('escarcelle', 'fr',
      { en: 'In the Middle Ages, it hung from your belt', fr: 'Au Moyen Âge, elle pendait à la ceinture' },
      { en: 'A large purse hung from the belt; today, the money one has.', fr: 'Grande bourse pendue à la ceinture ; par extension, l’argent qu’on a.' },
      ['purse', 'pouch', 'money', 'wallet', 'bourse', 'argent', 'porte-monnaie']),
    w('coquecigrue', 'fr',
      { en: 'Something you will never actually see', fr: 'Quelque chose qu’on ne verra jamais vraiment' },
      { en: 'An absurd idea or an imaginary creature; nonsense.', fr: 'Chimère, idée absurde, animal imaginaire.' },
      ['absurd', 'imaginary', 'nonsense', 'fantasy', 'chimere', 'imaginaire', 'baliverne']),
    w('vétille', 'fr',
      { en: 'Not worth arguing about', fr: 'Pas la peine de se disputer pour ça' },
      { en: 'A trifle; something of no importance.', fr: 'Chose insignifiante, sans importance.' },
      ['trifle', 'unimportant', 'detail', 'bagatelle', 'broutille', 'insignifian', 'importance']),
    w('hurluberlu', 'fr',
      { en: 'Not someone you would call ordinary', fr: 'Pas quelqu’un qu’on qualifierait d’ordinaire' },
      { en: 'An eccentric, scatterbrained person who acts oddly.', fr: 'Personne extravagante, qui agit de façon bizarre et étourdie.' },
      ['eccentric', 'oddball', 'weird', 'scatter', 'farfelu', 'excentrique', 'bizarre', 'original']),
    w('saugrenu', 'fr',
      { en: 'Could describe a very odd question', fr: 'Peut qualifier une question très étrange' },
      { en: 'Strange and absurd in a ridiculous way.', fr: 'Étrange, absurde et un peu ridicule.' },
      ['absurd', 'strange', 'odd', 'ridiculous', 'bizarre', 'etrange', 'ridicule', 'farfelu']),
    w('margoulin', 'fr',
      { en: 'Watch your wallet', fr: 'Surveillez votre portefeuille' },
      { en: 'A dishonest, unscrupulous businessman; a swindler.', fr: 'Commerçant ou homme d’affaires peu scrupuleux ; escroc.' },
      ['swindler', 'crook', 'dishonest', 'con', 'escroc', 'filou', 'malhonnete', 'arnaqu']),
    w('bisbille', 'fr',
      { en: 'Happens between neighbours over a hedge', fr: 'Arrive entre voisins pour une histoire de haie' },
      { en: 'A petty quarrel over something trivial.', fr: 'Petite querelle pour un motif futile.' },
      ['quarrel', 'argument', 'dispute', 'squabble', 'querelle', 'chamaill', 'dispute']),
    w('pérégrination', 'fr',
      { en: 'Globetrotters collect them', fr: 'Les globe-trotteurs en collectionnent' },
      { en: 'A long journey with many stops from place to place.', fr: 'Voyage long et compliqué, avec de nombreuses étapes.' },
      ['journey', 'travel', 'trip', 'wander', 'voyage', 'periple', 'deplacement']),
    w('subreptice', 'fr',
      { en: 'Not done in broad daylight', fr: 'Pas fait au grand jour' },
      { en: 'Done secretly or stealthily.', fr: 'Qui se fait en cachette, furtivement.' },
      ['secret', 'stealth', 'sneak', 'hidden', 'furtif', 'cache', 'discret', 'cachette']),
    w('chafouin', 'fr',
      { en: 'Describes a certain kind of face', fr: 'Décrit un certain genre de visage' },
      { en: 'Sly-looking, with a cunning, sneaky face.', fr: 'Qui a une mine rusée, sournoise.' },
      ['sly', 'sneaky', 'cunning', 'shifty', 'ruse', 'sournois', 'fourbe']),
    w('pantagruélique', 'fr',
      { en: 'Think of a giant from Rabelais', fr: 'Pensez à un géant de Rabelais' },
      { en: 'Enormous, especially of a meal: gargantuan.', fr: 'Énorme, en parlant d’un repas : gargantuesque.' },
      ['huge', 'enormous', 'gigantic', 'feast', 'enorme', 'copieu', 'gargantu', 'gigantesque']),
    w('zigouiller', 'fr',
      { en: 'Slang you’d hear in an old crime film', fr: 'De l’argot de vieux film policier' },
      { en: '(Slang) to kill someone.', fr: '(Familier) tuer quelqu’un.' },
      ['kill', 'murder', 'tuer', 'assassin']),
    w('esbroufe', 'fr',
      { en: 'Show-offs are experts at it', fr: 'Les frimeurs en sont experts' },
      { en: 'Showing off to impress or bluff people.', fr: 'Étalage de manières prétentieuses pour impressionner ; bluff.' },
      ['show off', 'bluff', 'impress', 'brag', 'frime', 'epate', 'impression']),
    w('carabistouille', 'fr',
      { en: 'Belgians say it a lot', fr: 'Les Belges l’emploient volontiers' },
      { en: 'Nonsense; a tall tale told to fool someone.', fr: 'Baliverne, bêtise, histoire racontée pour tromper.' },
      ['nonsense', 'lie', 'fib', 'tall tale', 'betise', 'baliverne', 'mensonge', 'blague']),
    w('pétaudière', 'fr',
      { en: 'A classroom when the teacher steps out', fr: 'Une classe quand le prof s’absente' },
      { en: 'A chaotic place where nobody is in charge.', fr: 'Lieu où règnent le désordre et la confusion, où chacun fait ce qu’il veut.' },
      ['chaos', 'mess', 'disorder', 'pagaille', 'bazar', 'desordre', 'foutoir']),
    w('rasséréner', 'fr',
      { en: 'What a calm voice can do', fr: 'Ce que peut faire une voix calme' },
      { en: 'To calm someone down and restore their peace of mind.', fr: 'Ramener au calme, rendre la sérénité.' },
      ['calm', 'reassur', 'soothe', 'calmer', 'rassur', 'apaiser', 'serenit']),
    w('brinquebaler', 'fr',
      { en: 'Think of an old cart on a bumpy road', fr: 'Pensez à une vieille charrette sur un chemin cabossé' },
      { en: 'To sway or jolt from side to side.', fr: 'Osciller, être secoué de côté et d’autre.' },
      ['sway', 'jolt', 'shake', 'wobble', 'rattle', 'secou', 'oscill', 'ballott']),
  ],
};

export const FOREIGN = [
  f('hygge', 'da',
    { en: 'A cosy, warm feeling of comfort and contentment, often with friends.', fr: 'Sentiment de confort chaleureux et de bien-être, souvent entre amis.' },
    ['cosy', 'cozy', 'comfort', 'warm', 'douillet', 'confort', 'bien-etre', 'chaleur']),
  f('saudade', 'pt',
    { en: 'A deep longing for someone or something that is absent or lost.', fr: 'Nostalgie profonde, manque de quelqu’un ou de quelque chose d’absent.' },
    ['longing', 'nostalgi', 'missing', 'miss', 'melanchol', 'manque']),
  f('Schadenfreude', 'de',
    { en: 'Pleasure felt at someone else’s misfortune.', fr: 'Joie ressentie face au malheur d’autrui.' },
    ['pleasure', 'misfortune', 'joy', 'happy', 'joie', 'malheur', 'plaisir']),
  f('wabi-sabi', 'ja',
    { en: 'Finding beauty in imperfection and in things that don’t last.', fr: 'Trouver de la beauté dans l’imperfection et l’éphémère.' },
    ['beauty', 'imperfect', 'beaute', 'imparfait', 'imperfection']),
  f('tsundoku', 'ja',
    { en: 'Buying books and letting them pile up unread.', fr: 'Acheter des livres et les laisser s’empiler sans les lire.' },
    ['book', 'unread', 'pile', 'livre', 'lire']),
  f('komorebi', 'ja',
    { en: 'Sunlight filtering through the leaves of trees.', fr: 'Lumière du soleil qui filtre à travers les feuilles des arbres.' },
    ['sunlight', 'sun', 'leaves', 'tree', 'soleil', 'feuille', 'arbre', 'lumiere']),
  f('ubuntu', 'zu',
    { en: 'Humanity towards others: “I am because we are”.', fr: 'Humanité envers les autres : « je suis parce que nous sommes ».' },
    ['humanity', 'community', 'together', 'others', 'humanite', 'communaute', 'ensemble', 'autres']),
  f('pole pole', 'sw',
    { en: 'Slowly, slowly — take it easy.', fr: 'Doucement, doucement — prends ton temps.' },
    ['slow', 'easy', 'calm', 'doucement', 'lentement', 'temps']),
  f('lagom', 'sv',
    { en: 'Just the right amount — not too much, not too little.', fr: 'Juste ce qu’il faut, ni trop ni trop peu.' },
    ['right amount', 'balance', 'moderat', 'enough', 'juste', 'equilibre', 'ni trop']),
  f('fika', 'sv',
    { en: 'A coffee break with something sweet, shared with others.', fr: 'Pause café accompagnée d’une douceur, entre amis ou collègues.' },
    ['coffee', 'break', 'cafe', 'pause']),
  f('gezellig', 'nl',
    { en: 'Cosy, pleasant and sociable (of a place or a moment).', fr: 'Convivial, chaleureux et agréable (un lieu, un moment).' },
    ['cosy', 'cozy', 'sociable', 'pleasant', 'convivial', 'chaleureu', 'agreable']),
  f('sobremesa', 'es',
    { en: 'Time spent chatting at the table after a meal.', fr: 'Moment passé à discuter à table après le repas.' },
    ['table', 'after', 'meal', 'talk', 'chat', 'conversation', 'repas', 'discut']),
  f('meraki', 'el',
    { en: 'Putting your soul, creativity and love into what you do.', fr: 'Mettre son âme, sa créativité et son amour dans ce qu’on fait.' },
    ['soul', 'love', 'passion', 'creativ', 'ame', 'amour']),
  f('hiraeth', 'cy',
    { en: 'Homesickness for a home you can’t return to, or that never was.', fr: 'Mal du pays pour un foyer où l’on ne peut revenir, ou qui n’a jamais existé.' },
    ['homesick', 'longing', 'home', 'nostalgi', 'mal du pays', 'foyer']),
  f('Kummerspeck', 'de',
    { en: 'Weight gained from eating to cope with sadness (literally “grief bacon”).', fr: 'Kilos pris en mangeant pour se consoler (littéralement « lard de chagrin »).' },
    ['weight', 'eat', 'sad', 'grief', 'poids', 'kilo', 'manger', 'chagrin', 'triste']),
  f('Backpfeifengesicht', 'de',
    { en: 'A face that makes you want to slap it.', fr: 'Une tête à claques.' },
    ['face', 'slap', 'punch', 'gifle', 'claque', 'tete', 'visage']),
  f('mamihlapinatapai', 'yag',
    { en: 'A look shared by two people who each want something to happen, but neither wants to go first.', fr: 'Un regard échangé par deux personnes qui veulent la même chose, mais dont aucune n’ose commencer.' },
    ['look', 'glance', 'both', 'first', 'regard', 'premier', 'oser']),
  f('ikigai', 'ja',
    { en: 'A reason for being; what makes life worth living.', fr: 'Raison d’être ; ce qui donne du sens à la vie.' },
    ['reason', 'purpose', 'meaning', 'life', 'raison', 'sens', 'vie']),
  f('dolce far niente', 'it',
    { en: 'The sweetness of doing nothing.', fr: 'La douceur de ne rien faire.' },
    ['nothing', 'relax', 'idle', 'rien', 'douceur', 'farniente']),
  f('culaccino', 'it',
    { en: 'The ring mark a wet glass leaves on a table.', fr: 'La marque laissée sur une table par un verre mouillé.' },
    ['mark', 'ring', 'glass', 'table', 'stain', 'trace', 'verre', 'marque', 'rond']),
  f('jayus', 'id',
    { en: 'A joke so badly told, or so unfunny, that you can’t help laughing.', fr: 'Une blague si mal racontée ou si peu drôle qu’on finit par en rire.' },
    ['joke', 'unfunny', 'bad', 'laugh', 'blague', 'nul', 'rire']),
  f('sisu', 'fi',
    { en: 'Stubborn determination and grit in the face of hardship.', fr: 'Détermination tenace et courage face à l’adversité.' },
    ['determin', 'grit', 'courage', 'persever', 'resilien', 'tenac', 'adversit']),
  f('gigil', 'tl',
    { en: 'The urge to squeeze or pinch something unbearably cute.', fr: 'L’envie irrésistible de serrer ou de pincer quelque chose de trop mignon.' },
    ['cute', 'squeeze', 'pinch', 'mignon', 'serrer', 'pincer']),
  f('toska', 'ru',
    { en: 'A deep anguish or restless longing, often with no clear cause.', fr: 'Angoisse ou vague à l’âme profond, souvent sans raison précise.' },
    ['anguish', 'longing', 'melanchol', 'sad', 'angoisse', 'vague a l', 'triste']),
  f('Waldeinsamkeit', 'de',
    { en: 'The feeling of being alone in the woods.', fr: 'Le sentiment d’être seul dans la forêt.' },
    ['alone', 'forest', 'wood', 'solitude', 'seul', 'foret', 'bois']),
  f('shlimazel', 'yi',
    { en: 'A person who is always unlucky.', fr: 'Une personne qui n’a jamais de chance.' },
    ['unlucky', 'bad luck', 'misfortune', 'malchan', 'poisse', 'chance']),
  f('kalsarikännit', 'fi',
    { en: 'Drinking alone at home in your underwear, with no plan to go out.', fr: 'Boire seul chez soi en sous-vêtements, sans intention de sortir.' },
    ['drink', 'home', 'underwear', 'alone', 'boire', 'maison', 'sous-vetement', 'seul']),
  f('utepils', 'no',
    { en: 'The first beer enjoyed outdoors in spring.', fr: 'La première bière bue dehors au printemps.' },
    ['beer', 'outside', 'outdoor', 'spring', 'biere', 'dehors', 'terrasse', 'printemps']),
  f('abbiocco', 'it',
    { en: 'The drowsiness you feel after a big meal.', fr: 'La somnolence qui suit un gros repas.' },
    ['sleepy', 'drowsy', 'tired', 'meal', 'somnolen', 'fatigue', 'repas', 'sieste']),
  f('age-otori', 'ja',
    { en: 'Looking worse after a haircut.', fr: 'Être moins beau après une coupe de cheveux.' },
    ['haircut', 'hair', 'worse', 'coupe', 'cheveux']),
  f('pana poʻo', 'haw',
    { en: 'Scratching your head to try to remember something.', fr: 'Se gratter la tête pour essayer de se souvenir de quelque chose.' },
    ['scratch', 'head', 'remember', 'gratter', 'tete', 'souvenir', 'rappeler']),
  f('tartle', 'sco',
    { en: 'Hesitating when introducing someone because you’ve forgotten their name.', fr: 'Hésiter en présentant quelqu’un parce qu’on a oublié son nom.' },
    ['forget', 'name', 'hesitat', 'introduc', 'oubli', 'nom', 'present']),
  f('cafuné', 'pt',
    { en: 'Tenderly running your fingers through someone’s hair.', fr: 'Passer tendrement les doigts dans les cheveux de quelqu’un.' },
    ['finger', 'hair', 'caress', 'stroke', 'doigt', 'cheveu', 'caresse']),
  f('dépaysement', 'fr',
    { en: 'The feeling of being out of your element somewhere unfamiliar.', fr: 'Le sentiment d’être hors de ses repères dans un lieu inconnu.' },
    ['foreign', 'unfamiliar', 'disorient', 'abroad', 'element', 'change of scenery']),
  f('jugaad', 'hi',
    { en: 'A clever, improvised fix made with whatever is at hand.', fr: 'Une solution ingénieuse bricolée avec les moyens du bord.' },
    ['fix', 'improvis', 'hack', 'clever', 'bricol', 'systeme d', 'debrouill']),
  f('Wanderlust', 'de',
    { en: 'A strong desire to travel and explore the world.', fr: 'Une forte envie de voyager et de découvrir le monde.' },
    ['travel', 'explore', 'wander', 'voyag', 'decouvr']),
  f('yaʿburnī', 'ar',
    { en: '“You bury me”: hoping to die before someone you love, so as not to live without them.', fr: '« Tu m’enterres » : espérer mourir avant quelqu’un qu’on aime pour ne pas vivre sans lui.' },
    ['bury', 'die', 'death', 'love', 'enterr', 'mourir', 'mort', 'aime']),
  f('poronkusema', 'fi',
    { en: 'The distance a reindeer can travel before needing a break (about 7.5 km).', fr: 'La distance qu’un renne parcourt avant de devoir faire une pause (environ 7,5 km).' },
    ['reindeer', 'distance', 'renne']),
  f('iktsuarpok', 'iu',
    { en: 'Going outside again and again to check whether someone is coming.', fr: 'Sortir sans cesse voir si quelqu’un arrive.' },
    ['wait', 'check', 'coming', 'arriv', 'attend', 'sortir', 'outside']),
  f('sawubona', 'zu',
    { en: 'A Zulu greeting meaning “I see you”.', fr: 'Une salutation zouloue qui signifie « je te vois ».' },
    ['hello', 'greeting', 'see you', 'bonjour', 'salut', 'je te vois']),
  f('akwaaba', 'ak',
    { en: 'Welcome.', fr: 'Bienvenue.' },
    ['welcome', 'bienvenu']),
  f('teranga', 'wo',
    { en: 'Senegalese hospitality: warmly welcoming guests and sharing with them.', fr: 'L’hospitalité sénégalaise : accueillir chaleureusement ses hôtes et partager avec eux.' },
    ['hospitality', 'welcome', 'share', 'hospitalit', 'accueil', 'partag']),
  f('harambee', 'sw',
    { en: '“Let’s pull together”: a community working as one for a shared goal.', fr: '« Tirons ensemble » : une communauté qui s’unit pour un but commun.' },
    ['together', 'community', 'pull', 'unity', 'ensemble', 'communaut', 'entraide', 'unit']),
  f('mbote', 'ln',
    { en: 'Hello (a greeting).', fr: 'Bonjour (une salutation).' },
    ['hello', 'hi', 'greeting', 'bonjour', 'salut']),
];
